"""Fetch Google variable fonts and bake static, overlap-free instances.

Chromium on Linux rasterises large glyphs as paths, and overlapping contours
in the variable fonts show up as notches (visible as notches on some glyphs).
Instancing with OverlapMode.REMOVE gives clean outlines at any size.

Usage: python3 tools/fonts.py   (needs: fonttools brotli skia-pathops)
"""
import os, re, subprocess, tempfile
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont, OverlapMode

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'fonts')
UA = ('Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
      '(KHTML, like Gecko) Chrome/140.0 Safari/537.36')
CSS_URL = ('https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,100..900'
           '&family=JetBrains+Mono:wght@400..800&display=block')
SUBSETS = ['latin', 'latin-ext', 'cyrillic']

# css family -> (source family, axis location, css weight)
INSTANCES = {
    'Inter':        [('Inter', {'wght': w, 'opsz': 22}, w) for w in (400, 500, 600, 700, 800)],
    'InterDisplay': [('Inter', {'wght': w, 'opsz': 32}, w) for w in (500, 600, 700, 800, 900)],
    'Mono':         [('JetBrains Mono', {'wght': w}, w) for w in (500, 700)],
}

def main():
    os.makedirs(OUT, exist_ok=True)
    tmp = tempfile.mkdtemp()
    css = subprocess.run(['curl', '-sS', '-A', UA, CSS_URL], check=True,
                         capture_output=True, text=True).stdout
    src = {}  # (family, subset) -> (path, unicode-range)
    for subset, block in re.findall(r'/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})', css, re.S):
        if subset not in SUBSETS:
            continue
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        url = re.search(r'url\((https://[^)]+)\)', block).group(1)
        urange = re.search(r'unicode-range: ([^;]+);', block).group(1)
        path = os.path.join(tmp, f"{fam.replace(' ', '')}-{subset}.woff2")
        subprocess.run(['curl', '-sS', '-o', path, url], check=True)
        src[(fam, subset)] = (path, urange)

    for f in os.listdir(OUT):
        if f.endswith('.woff2') or f == 'fonts.css':
            os.remove(os.path.join(OUT, f))
    faces = []
    for css_family, items in INSTANCES.items():
        for source_family, loc, weight in items:
            for subset in SUBSETS:
                path, urange = src[(source_family, subset)]
                vf = TTFont(path)
                inst = instantiateVariableFont(vf, loc, overlap=OverlapMode.REMOVE)
                inst.flavor = 'woff2'
                name = f'{css_family}-{weight}-{subset}.woff2'
                inst.save(os.path.join(OUT, name))
                faces.append(
                    "@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                    "font-display:block;src:url(%s) format('woff2');unicode-range:%s;}"
                    % (css_family, weight, name, urange))
    with open(os.path.join(OUT, 'fonts.css'), 'w') as fh:
        fh.write('/* Generated by tools/fonts.py - static, overlap-free instances (SIL OFL fonts) */\n')
        fh.write('\n'.join(faces) + '\n')
    print(len(faces), 'faces written to', os.path.normpath(OUT))

if __name__ == '__main__':
    main()
