// Bundles the Lucide icons used by the reel into src/icons.js so the page has no async icon loading.
import { readFileSync, writeFileSync } from 'node:fs';

const NAMES = [
  'users', 'user-plus', 'user-round', 'building-2', 'kanban', 'list-checks', 'package', 'file-text',
  'receipt', 'credit-card', 'life-buoy', 'megaphone', 'bell', 'message-square', 'calendar-days',
  'layout-dashboard', 'chart-column', 'shield-check', 'folder-open', 'plug', 'workflow', 'zap',
  'sliders-horizontal', 'settings', 'globe', 'instagram', 'phone', 'phone-missed', 'star', 'check',
  'arrow-right', 'trophy', 'filter', 'git-branch', 'file-spreadsheet', 'triangle-alert', 'circle-help',
  'mail', 'calendar-clock', 'banknote', 'download', 'circle-check', 'sparkles', 'landmark',
  'arrow-up-right', 'trending-up', 'languages', 'badge-check', 'file-check', 'wallet', 'handshake',
  'target', 'flame', 'mic', 'send', 'split', 'clock', 'rocket', 'inbox', 'at-sign', 'x',
];

const out = {};
for (const n of NAMES) {
  const svg = readFileSync(new URL(`../node_modules/lucide-static/icons/${n}.svg`, import.meta.url), 'utf8');
  out[n] = svg.slice(svg.indexOf('>', svg.indexOf('<svg')) + 1, svg.lastIndexOf('</svg>')).replace(/\s+/g, ' ').trim();
}
writeFileSync(new URL('../src/icons.js', import.meta.url),
  '// Generated by scripts/gen-icons.mjs from lucide-static (ISC license). Do not edit by hand.\n' +
  `export const ICONS = ${JSON.stringify(out, null, 0)};\n`);
console.log('icons:', Object.keys(out).length);
