// Generates src/generated/assets.js: inline Lucide icon markup + a real QR code
// for https://www.ineed.now (used on the voucher card).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const iconDir = path.join(root, 'node_modules/lucide-static/icons');

const ICONS = [
  // modules
  'building-2', 'file-signature', 'package', 'calendar-range', 'map', 'plane-takeoff', 'percent',
  'inbox', 'calendar-check', 'id-card', 'credit-card', 'list-checks', 'kanban', 'clipboard-list',
  'bus', 'receipt', 'hand-coins', 'arrow-left-right', 'trending-up', 'handshake', 'store',
  'layout-dashboard', 'chart-column', 'folder-open', 'user-cog', 'settings', 'plug', 'workflow',
  'text-cursor-input', 'megaphone',
  // ui
  'hotel', 'bed-double', 'plane', 'map-pin', 'ticket', 'utensils', 'cable-car', 'compass',
  'calendar-days', 'users', 'user-round', 'file-spreadsheet', 'mail', 'message-circle',
  'phone-missed', 'badge-check', 'shield-check', 'qr-code', 'scan-line', 'wallet', 'coins',
  'languages', 'zap', 'lock', 'lock-open', 'file-text', 'calculator', 'bell', 'bell-ring',
  'triangle-alert', 'check', 'circle-check-big', 'globe', 'arrow-right', 'arrow-up-right',
  'mouse-pointer-2', 'plus', 'sparkles', 'armchair', 'gauge', 'clock', 'send', 'stamp',
  'file-warning', 'user-check', 'users-round', 'car-front', 'circle-plus', 'layers', 'route',
];

const out = {};
for (const name of ICONS) {
  const svg = fs.readFileSync(path.join(iconDir, `${name}.svg`), 'utf8');
  const inner = svg
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>[\s\S]*$/, '')
    .replace(/\s+/g, ' ')
    .trim();
  out[name] = inner;
}

const qr = QRCode.create('https://www.ineed.now', { errorCorrectionLevel: 'M' });
const n = qr.modules.size;
let d = '';
for (let y = 0; y < n; y++) {
  for (let x = 0; x < n; x++) {
    if (qr.modules.get(x, y)) d += `M${x} ${y}h1v1h-1z`;
  }
}

const js = `// AUTO-GENERATED by scripts/build-assets.mjs — do not edit.
// Icons: Lucide (ISC license) https://lucide.dev
window.ICONS = ${JSON.stringify(out)};
window.QR = { size: ${n}, path: ${JSON.stringify(d)} };
`;
fs.writeFileSync(path.join(root, 'src/generated/assets.js'), js);
console.log(`wrote ${Object.keys(out).length} icons, QR ${n}x${n}`);
