// Collects the Lucide icons the reel uses into one JS file (inner SVG markup only).
import fs from 'fs';
const names = ['clock','file-warning','users','trending-down','shield-check','globe','coins','check',
  'lock','arrow-right','mouse-pointer-2','circle-check','sparkles','triangle-alert','calendar-range',
  'receipt','chart-column','briefcase','languages'];
const out = {};
for (const n of names) {
  const svg = fs.readFileSync(`node_modules/lucide-static/icons/${n}.svg`, 'utf8');
  out[n] = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').replace(/\s+/g, ' ').trim();
}
// Instagram glyph (Lucide dropped brand icons; this is the classic outline form).
out['instagram'] = '<rect width="20" height="20" x="2" y="2" rx="5" ry="5"/><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"/><line x1="17.5" x2="17.51" y1="6.5" y2="6.5"/>';
fs.writeFileSync('src/js/icons.js', '// Generated by scripts/gen-icons.mjs from lucide-static (ISC).\nwindow.ICONS = ' + JSON.stringify(out, null, 1) + ';\n');
console.log('icons:', Object.keys(out).length);
